### ISSUE TITLE
Fluid Crafter and Resource Combiner fluid visual bug

### ISSUE THREAD

**Issue by Sedus** [benbenlaw/techopolis#35] opened 2022-02-13 14:28 UTC
Modpack version: B11.0
Mode: Skyblock mode
Fluid Crafter don't show fluid amount correctly. Shows the same amount after use.
Same with Resource Combiner.

https://imgur.com/a/GbFHqxD

**Comment by benbenlaw** [comment] 2022-02-18 09:27
duplicate of #24

**Closed as completed by benbenlaw** 2022-02-18 09:27 UTC
